<a href="https://colab.research.google.com/github/vpanabak/python-basics-assignment/blob/main/Copy_of_Batch2_Pandas_Groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
titanic = sns.load_dataset("titanic")

# Clean missing values first (from Section 1)
titanic = titanic.drop(columns=["deck"])
titanic["age"] = titanic["age"].fillna(titanic["age"].median())
titanic["embarked"] = titanic["embarked"].fillna(titanic["embarked"].mode()[0])

In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [ ]:
grouped = titanic.groupby("pclass")

for i,j in grouped:
    print(i)
    print(j)

1
     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First
3           1       1  female  35.0      1      0  53.1000        S  First
6           0       1    male  54.0      0      0  51.8625        S  First
11          1       1  female  58.0      0      0  26.5500        S  First
23          1       1    male  28.0      0      0  35.5000        S  First
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
871         1       1  female  47.0      1      1  52.5542        S  First
872         0       1    male  33.0      0      0   5.0000        S  First
879         1       1  female  56.0      0      1  83.1583        C  First
887         1       1  female  19.0      0      0  30.0000        S  First
889         1       1    male  26.0      0      0  30.0000        C  First

       who  adult_male  embark_town alive  alone
1    woman       False    Cherbourg   yes  False
3    woman       False  Southampton   yes  False
6      man        True  Southampton    no   True
11   woman       False  Southampton   yes   True
23     man        True  Southampton   yes   True
..     ...         ...          ...   ...    ...
871  woman       False  Southampton   yes  False
872    man        True  Southampton    no   True
879  woman       False    Cherbourg   yes  False
887  woman       False  Southampton   yes   True
889    man        True    Cherbourg   yes   True

[216 rows x 14 columns]
2
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
9           1       2  female  14.0      1      0  30.0708        C  Second
15          1       2  female  55.0      0      0  16.0000        S  Second
17          1       2    male  28.0      0      0  13.0000        S  Second
20          0       2    male  35.0      0      0  26.0000        S  Second
21          1       2    male  34.0      0      0  13.0000        S  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
866         1       2  female  27.0      1      0  13.8583        C  Second
874         1       2  female  28.0      1      0  24.0000        C  Second
880         1       2  female  25.0      0      1  26.0000        S  Second
883         0       2    male  28.0      0      0  10.5000        S  Second
886         0       2    male  27.0      0      0  13.0000        S  Second

       who  adult_male  embark_town alive  alone
9    child       False    Cherbourg   yes  False
15   woman       False  Southampton   yes   True
17     man        True  Southampton   yes   True
20     man        True  Southampton    no   True
21     man        True  Southampton   yes   True
..     ...         ...          ...   ...    ...
866  woman       False    Cherbourg   yes  False
874  woman       False    Cherbourg   yes  False
880  woman       False  Southampton   yes  False
883    man        True  Southampton    no   True
886    man        True  Southampton    no   True

[184 rows x 14 columns]
3
     survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S  Third
2           1       3  female  26.0      0      0   7.9250        S  Third
4           0       3    male  35.0      0      0   8.0500        S  Third
5           0       3    male  28.0      0      0   8.4583        Q  Third
7           0       3    male   2.0      3      1  21.0750        S  Third
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
882         0       3  female  22.0      0      0  10.5167        S  Third
884         0       3    male  25.0      0      0   7.0500        S  Third
885         0       3  female  39.0      0      5  29.1250        Q  Third
888         0       3  female  28.0      1      2  23.4500        S  Third
890         0       3    male  32.0      0      0   7.7500        Q  Third

       who  adult_male  embark_town alive  alone
0      man        True  Southampton    no  False
2    woman       False  Southampton   yes   True
4      man        True  Southampton    no   True
5      man        True   Queenstown    no   True
7    child       False  Southampton    no  False
..     ...         ...          ...   ...    ...
882  woman       False  Southampton    no   True
884    man        True  Southampton    no   True
885  woman       False   Queenstown    no  False
888  woman       False  Southampton    no  False
890    man        True   Queenstown    no   True

[491 rows x 14 columns]

In [ ]:
titanic.groupby(["pclass"])

In [ ]:
# 1. What was the survival rate by passenger class?

survival_by_class = titanic.groupby("pclass")["survived"].mean()
print(survival_by_class)

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

In [ ]:
count_by_class = titanic.groupby("pclass")["survived"].count()
print(count_by_class)

pclass
1    216
2    184
3    491
Name: survived, dtype: int64

In [ ]:
survival_by_sex = titanic.groupby("sex")["survived"].mean()
print(survival_by_sex)

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [ ]:
survival_by_sex_class = titanic.groupby(["sex", "pclass"])["survived"].mean()
survival_by_sex_class

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

In [ ]:
survival_by_sex_class = titanic.groupby(["pclass","sex" ])["survived"].mean()
survival_by_sex_class

pclass  sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: survived, dtype: float64

In [ ]:
survival_by_sex_class = titanic.groupby(["sex", "pclass"])["survived"].mean()
survival_by_sex_class

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

In [ ]:
type(survival_by_sex_class)

pandas.core.series.Series

In [ ]:
survival_by_sex_class = titanic.groupby(["sex", "pclass"])["survived"].mean().reset_index()
survival_by_sex_class

      sex  pclass  survived
0  female       1  0.968085
1  female       2  0.921053
2  female       3  0.500000
3    male       1  0.368852
4    male       2  0.157407
5    male       3  0.135447

In [ ]:
# What is the avergae fare paid by class and embarkation port?

In [ ]:
fare_by_class_port = titanic.groupby(["pclass", "embarked"])["fare"].mean().reset_index()
fare_by_class_port

   pclass embarked        fare
0       1        C  104.718529
1       1        Q   90.000000
2       1        S   70.514244
3       2        C   25.358335
4       2        Q   12.350000
5       2        S   20.327439
6       3        C   11.214083
7       3        Q   11.183393
8       3        S   14.644083

In [ ]:
fare_by_class_port = titanic.groupby(["pclass", "embarked"])["fare"].max().reset_index()
fare_by_class_port

   pclass embarked      fare
0       1        C  512.3292
1       1        Q   90.0000
2       1        S  263.0000
3       2        C   41.5792
4       2        Q   12.3500
5       2        S   73.5000
6       3        C   22.3583
7       3        Q   29.1250
8       3        S   69.5500

In [ ]:
import pandas as pd

# Back to our sales demo data
sales_data = {
    "Region":   ["North", "South", "North", "East", "South", "East", "North", "South", "East", "North"],
    "Product":  ["A", "B", "A", "C", "B", "A", "C", "A", "B", "B"],
    "Sales":    [250, 150, 300, 200, 180, 220, 190, 210, 240, 280],
    "Quantity": [5, 3, 6, 4, 3, 4, 3, 4, 5, 6]
}
df = pd.DataFrame(sales_data)
df

  Region Product  Sales  Quantity
0  North       A    250         5
1  South       B    150         3
2  North       A    300         6
3   East       C    200         4
4  South       B    180         3
5   East       A    220         4
6  North       C    190         3
7  South       A    210         4
8   East       B    240         5
9  North       B    280         6

In [ ]:
# What is the sum, mean and count of sales per every region?

In [ ]:
df.groupby("Region")["Sales"].sum()    # Just sum
df.groupby("Region")["Sales"].mean()   # Just mean
df.groupby("Region")["Sales"].count()  # Just count

In [ ]:
df.groupby("Region")["Sales"].agg(["sum", "mean", "count", "min", "max"])

         sum   mean  count  min  max
Region
East     660  220.0      3  200  240
North   1020  255.0      4  190  300
South    540  180.0      3  150  210

In [ ]:
df.groupby(["Region", "Product"])["Sales"].agg(["sum", "mean", "count", "min", "max"])

                sum   mean  count  min  max
Region Product
East   A        220  220.0      1  220  220
       B        240  240.0      1  240  240
       C        200  200.0      1  200  200
North  A        550  275.0      2  250  300
       B        280  280.0      1  280  280
       C        190  190.0      1  190  190
South  A        210  210.0      1  210  210
       B        330  165.0      2  150  180

In [ ]:
df.groupby(["Region", "Product"])["Sales"].agg(["sum", "mean", "count", "min", "max"]).reset_index()

  Region Product  sum   mean  count  min  max
0   East       A  220  220.0      1  220  220
1   East       B  240  240.0      1  240  240
2   East       C  200  200.0      1  200  200
3  North       A  550  275.0      2  250  300
4  North       B  280  280.0      1  280  280
5  North       C  190  190.0      1  190  190
6  South       A  210  210.0      1  210  210
7  South       B  330  165.0      2  150  180

In [ ]:
# Different stats for Sales vs Quantity
result = df.groupby("Region").agg({
    "Sales": ["sum", "mean"],
    "Quantity": ["sum", "max"]
})
print(result)

       Sales        Quantity
         sum   mean      sum max
Region
East     660  220.0       13   5
North   1020  255.0       20   6
South    540  180.0       10   4

In [ ]:
# Different stats for Sales vs Quantity
result = df.groupby("Region").agg({
    "Sales": ["sum", "mean"],
    "Quantity": ["sum", "max"]
}).reset_index()
result

  Region Sales        Quantity
           sum   mean      sum max
0   East   660  220.0       13   5
1  North  1020  255.0       20   6
2  South   540  180.0       10   4

In [ ]:
columns = ["Region", "Sales_sum", "Sales_mean", "Quantity_sum", "Quantity_max"]
result.columns = columns
result

  Region  Sales_sum  Sales_mean  Quantity_sum  Quantity_max
0   East        660       220.0            13             5
1  North       1020       255.0            20             6
2  South        540       180.0            10             4

In [ ]:
'''
I want a table that will tellme
    1. How many survived in each classs
    2/ Survivial rate
    3. total passengers
    4. Average anmd median age\
    5. average and maximum fare
'''

'\nI want a table that will tellme\n\n\n'

In [ ]:
result = titanic.groupby("pclass").agg({
    "survived": ["sum", "mean", "count"],
    "age" : ["mean", "median"],
    "fare" : ["mean", "max"]
}).reset_index()
result

  pclass survived                        age              fare
              sum      mean count       mean median       mean       max
0      1      136  0.629630   216  36.812130   35.0  84.154687  512.3292
1      2       87  0.472826   184  29.765380   28.0  20.662183   73.5000
2      3      119  0.242363   491  25.932627   28.0  13.675550   69.5500

# Named Aggregations

In [ ]:
result = titanic.groupby("pclass").agg(
    total_passengers=("survived", "count"),
    survivors=("survived", "sum"),
    survival_rate=("survived", "mean"),
    avg_age=("age", "mean"),
    avg_fare=("fare", "mean")
).reset_index()

result

   pclass  total_passengers  survivors  survival_rate    avg_age   avg_fare
0       1               216        136       0.629630  36.812130  84.154687
1       2               184         87       0.472826  29.765380  20.662183
2       3               491        119       0.242363  25.932627  13.675550